name: adhoc-tweet
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'message you want to tweet'
        required: true
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      uses: devigned/go-twitter-action
        with:
          message: Hello from adhoc action!